/**
 * CaseStudy — the shared data model for the categorised client pages.
 *
 * Some client rooms aren't one commission but a body of work made of several
 * smaller ones — an independent practice's many brands, a newsroom's editorial
 * output. These read as a set of CATEGORIES, each a small case study in its own
 * right: a headline, the challenge it answered, a description of the solution,
 * and its plates.
 *
 * Driven the same way as the other bespoke pages — content on the filesystem
 * under public/content/clients/<slug>/work/<folder>/, generated by
 * scripts/prepare-<slug>-experience.mjs. Each folder carries a `_plates.json`
 * manifest (curated order + intrinsic dimensions) so the gallery can lay the
 * plates out at their true aspect ratios without cropping.
 */

/** One image in a category, with the intrinsic size next/image needs. */
export interface CasePlate {
  url: string;
  w: number;
  h: number;
  name: string;
}

/** One categorised case study within a client page. */
export interface CaseCategory {
  id: string;
  /** Folder under work/ holding this category's plates + _plates.json. */
  folder: string;
  /** The brand or strand name. */
  name: string;
  /** The kind of work — the small mono eyebrow ("Brand system · Website"). */
  kind: string;
  /** The expressive one-line claim. */
  headline: string;
  /** The problem this work answered. */
  challenge: string;
  /** What was made, and why it worked. */
  description: string;
  /** Per-category accent hue. */
  accent: string;
  /** Optional live site to link out to. */
  site?: string;
}

/** A full categorised client page. */
export interface CaseStudyConfig {
  slug: string;
  /** Small eyebrow above the title ("Selected — Independent practice"). */
  eyebrow: string;
  /** The room's name. */
  title: string;
  /** The expressive serif line under the title. */
  tagline: string;
  /** The opening paragraph. */
  intro: string;
  /** Small mono meta lines (site, place, years). */
  metaLines: string[];
  /** Optional mark shown beside the header. */
  logo?: string;
  /** The quiet closing line. */
  footerNote: string;
  categories: CaseCategory[];
}
