/**
 * CaseStudy — the shared data model for the categorised client pages.
 *
 * Some client rooms aren't one commission but a body of work made of several
 * smaller ones — an independent practice's many brands, a newsroom's editorial
 * output. These read as a set of CATEGORIES, each a small case study in its own
 * right: a headline, the challenge it answered, a description of the solution,
 * and its plates.
 *
 * Driven the same way as the other bespoke pages — content on the filesystem
 * under public/content/clients/<slug>/work/<folder>/, generated by
 * scripts/prepare-<slug>-experience.mjs. Each folder carries a `_plates.json`
 * manifest (curated order + intrinsic dimensions) so the gallery can lay the
 * plates out at their true aspect ratios without cropping.
 */

/** One image in a category, with the intrinsic size next/image needs. */
export interface CasePlate {
  url: string;
  w: number;
  h: number;
  name: string;
}

/** One categorised case study within a client page. */
export interface CaseCategory {
  id: string;
  /** Folder under work/ holding this category's plates + _plates.json. */
  folder: string;
  /** The brand or strand name. */
  name: string;
  /** The kind of work — the small mono eyebrow ("Brand system · Website"). */
  kind: string;
  /** The expressive one-line claim. */
  headline: string;
  /** The problem this work answered. */
  challenge: string;
  /** What was made, and why it worked. */
  description: string;
  /** Per-category accent hue. */
  accent: string;
  /** Optional live site to link out to. */
  site?: string;
  /** How this category shows its plates. Absent = fall back to the config's
   *  own `presentation`, and absent there too = the standard CaseGallery grid.
   *  "coverflow" is the 3D flow.
   *  ⚠ ABS now sets this at CONFIG level (all twelve categories flow), so this
   *  per-category field is only for overriding one section against the room. */
  presentation?: "coverflow";
}

/** A full categorised client page. */
export interface CaseStudyConfig {
  slug: string;
  /** Small eyebrow above the title ("Selected — Independent practice"). */
  eyebrow: string;
  /** The room's name. Always set — it is the accessible name and the <title>
   *  even when `titleLogo` replaces it visually. */
  title: string;
  /** Print the brand's own logo in place of the typeset title. The <h1> stays,
   *  with `title` as its alt text, so the heading is unchanged to a screen
   *  reader and to search. ABS uses this; Newsmobile does not. */
  titleLogo?: string;
  /** Default presentation for EVERY category in this room. A category may
   *  still override it. */
  presentation?: "coverflow";
  /** Wrap the room in one font family, e.g. ABS's Barlow. A bare Tailwind
   *  class, applied to the page root so every child inherits it. */
  fontClass?: string;
  /** Show the numbered category index under the intro. Defaults to TRUE, so
   *  Newsmobile is untouched; ABS sets it false at the owner's request. */
  showIndex?: boolean;
  /** The expressive serif line under the title. */
  tagline: string;
  /** The opening paragraph. */
  intro: string;
  /** Small mono meta lines (site, place, years). */
  metaLines: string[];
  /** Optional mark shown beside the header. */
  logo?: string;
  /** Optional muted film behind the whole room, at low opacity. Supply a
   *  poster too — reduced-motion viewers get the still instead. */
  backdrop?: { src: string; poster: string };
  /** The quiet closing line. */
  footerNote: string;
  categories: CaseCategory[];
}
